// src/components/PivotSkeleton.vue
<script setup lang="ts">
/**
 * Pivot Table Skeleton + Data Display
 * Visual layout for pivot configuration and results
 */
import { computed, ref } from 'vue'
import type { AggregationFunction, PivotResult, PivotValueField } from '../types'
import { useLicense } from '../composables/useLicense'

const props = defineProps<{
  rowFields: string[]
  columnFields: string[]
  valueFields: PivotValueField[]
  isConfigured: boolean
  draggingField: string | null
  pivotResult: PivotResult | null
  fontSize?: 'xs' | 'sm' | 'base'
}>()

const emit = defineEmits<{
  (e: 'addRowField', field: string): void
  (e: 'removeRowField', field: string): void
  (e: 'addColumnField', field: string): void
  (e: 'removeColumnField', field: string): void
  (e: 'addValueField', field: string, aggregation: AggregationFunction): void
  (e: 'removeValueField', field: string, aggregation: AggregationFunction): void
  (e: 'updateAggregation', field: string, oldAgg: AggregationFunction, newAgg: AggregationFunction): void
  (e: 'reorderRowFields', fields: string[]): void
  (e: 'reorderColumnFields', fields: string[]): void
}>()

const { showWatermark, canUsePivot, isDemo } = useLicense()

// Drag state
const dragOverArea = ref<'row' | 'column' | 'value' | null>(null)

// Aggregation labels
const aggregationLabels: Record<AggregationFunction, string> = {
  sum: 'Sum',
  count: 'Count',
  avg: 'Average',
  min: 'Min',
  max: 'Max',
  countDistinct: 'Count Distinct',
}

function getAggregationLabel(fn: AggregationFunction): string {
  return aggregationLabels[fn]
}

function getAggSymbol(agg: AggregationFunction): string {
  const symbols: Record<AggregationFunction, string> = {
    sum: 'Σ',
    count: '#',
    avg: 'x̄',
    min: '↓',
    max: '↑',
    countDistinct: '◇',
  }
  return symbols[agg] || 'Σ'
}

// Font size
const currentFontSize = ref(props.fontSize || 'xs')
const fontSizeOptions = [
  { value: 'xs', label: 'S' },
  { value: 'sm', label: 'M' },
  { value: 'base', label: 'L' },
] as const

// Sorting
type SortDirection = 'asc' | 'desc'
type SortTarget = 'row' | number
const sortDirection = ref<SortDirection>('asc')
const sortTarget = ref<SortTarget>('row')

function toggleSort(target: SortTarget = 'row') {
  if (sortTarget.value === target) {
    sortDirection.value = sortDirection.value === 'asc' ? 'desc' : 'asc'
  }
  else {
    sortTarget.value = target
    sortDirection.value = 'asc'
  }
}

// Sorted row indices
const sortedRowIndices = computed(() => {
  if (!props.pivotResult)
    return []

  const indices = props.pivotResult.rowHeaders.map((_, i) => i)
  const headers = props.pivotResult.rowHeaders
  const data = props.pivotResult.data

  indices.sort((a, b) => {
    let cmp: number

    if (sortTarget.value === 'row') {
      const aHeader = headers[a]?.join(' / ') || ''
      const bHeader = headers[b]?.join(' / ') || ''
      cmp = aHeader.localeCompare(bHeader, undefined, { numeric: true, sensitivity: 'base' })
    }
    else {
      const colIdx = sortTarget.value as number
      const aVal = data[a]?.[colIdx]?.value ?? null
      const bVal = data[b]?.[colIdx]?.value ?? null

      if (aVal === null && bVal === null)
        cmp = 0
      else if (aVal === null)
        cmp = 1
      else if (bVal === null)
        cmp = -1
      else cmp = aVal - bVal
    }

    return sortDirection.value === 'asc' ? cmp : -cmp
  })

  return indices
})

// Column headers
const columnHeaderCells = computed(() => {
  if (!props.pivotResult || props.pivotResult.headers.length === 0) {
    return [props.valueFields.map(vf => ({
      label: `${vf.field} (${getAggregationLabel(vf.aggregation)})`,
      colspan: 1,
    }))]
  }

  const result: Array<Array<{ label: string, colspan: number }>> = []

  for (let level = 0; level < props.pivotResult.headers.length; level++) {
    const headerRow = props.pivotResult.headers[level]
    const cells: Array<{ label: string, colspan: number }> = []

    let i = 0
    while (i < headerRow.length) {
      const value = headerRow[i]
      let colspan = 1

      while (i + colspan < headerRow.length && headerRow[i + colspan] === value) {
        colspan++
      }

      cells.push({ label: value, colspan })
      i += colspan
    }

    result.push(cells)
  }

  return result
})

// Selection for copy support
const selectedCell = ref<{ row: number, col: number } | null>(null)
function handleCellClick(rowIndex: number, colIndex: number) {
  selectedCell.value = { row: rowIndex, col: colIndex }
}
function isCellSelected(rowIndex: number, colIndex: number): boolean {
  return selectedCell.value?.row === rowIndex && selectedCell.value?.col === colIndex
}

// Drag handlers
function handleDragOver(area: 'row' | 'column' | 'value', event: DragEvent) {
  event.preventDefault()
  event.dataTransfer!.dropEffect = 'move'
  dragOverArea.value = area
}

function handleDragLeave() {
  dragOverArea.value = null
}

function handleDrop(area: 'row' | 'column' | 'value', event: DragEvent) {
  event.preventDefault()
  const field = event.dataTransfer?.getData('text/plain')

  if (field) {
    if (props.rowFields.includes(field))
      emit('removeRowField', field)
    if (props.columnFields.includes(field))
      emit('removeColumnField', field)
    const existingValue = props.valueFields.find(v => v.field === field)
    if (existingValue)
      emit('removeValueField', field, existingValue.aggregation)

    switch (area) {
      case 'row':
        emit('addRowField', field)
        break
      case 'column':
        emit('addColumnField', field)
        break
      case 'value':
        emit('addValueField', field, 'sum')
        break
    }
  }
  dragOverArea.value = null
}

// Column width
const rowHeaderWidth = ref(180)
const dataColWidth = ref(80)
</script>

<template>
  <div
    class="vpg-pivot-skeleton"
    :class="[
      `vpg-font-${currentFontSize}`,
      { 'vpg-is-dragging': draggingField },
    ]"
  >
    <!-- Header Bar -->
    <div class="vpg-skeleton-header">
      <div class="vpg-skeleton-title">
        <svg class="vpg-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z" />
        </svg>
        <span>Pivot Table</span>
      </div>

      <div class="vpg-header-right">
        <div v-if="isConfigured" class="vpg-config-summary">
          <span class="vpg-summary-badge vpg-rows">{{ rowFields.length }} row{{ rowFields.length !== 1 ? 's' : '' }}</span>
          <span class="vpg-summary-badge vpg-cols">{{ columnFields.length }} col{{ columnFields.length !== 1 ? 's' : '' }}</span>
          <span class="vpg-summary-badge vpg-vals">{{ valueFields.length }} val{{ valueFields.length !== 1 ? 's' : '' }}</span>
        </div>

        <div v-if="isConfigured && pivotResult" class="vpg-font-size-toggle">
          <button
            v-for="opt in fontSizeOptions"
            :key="opt.value"
            class="vpg-font-size-btn"
            :class="{ active: currentFontSize === opt.value }"
            @click="currentFontSize = opt.value"
          >
            {{ opt.label }}
          </button>
        </div>
      </div>
    </div>

    <!-- License Required Message -->
    <div v-if="!canUsePivot" class="vpg-pro-required">
      <div class="vpg-pro-content">
        <svg class="vpg-pro-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
        </svg>
        <h3>Pro Feature</h3>
        <p>Pivot Table functionality requires a Pro license.</p>
        <a href="https://tiny-pivot.com/pricing" target="_blank" class="vpg-pro-link">
          Get Pro License →
        </a>
      </div>
    </div>

    <!-- Content when licensed -->
    <template v-else>
      <!-- Config Bar -->
      <div class="vpg-config-bar">
        <!-- Row drop zone -->
        <div
          class="vpg-drop-zone vpg-row-zone"
          :class="{ 'vpg-drag-over': dragOverArea === 'row' }"
          @dragover="handleDragOver('row', $event)"
          @dragleave="handleDragLeave"
          @drop="handleDrop('row', $event)"
        >
          <div class="vpg-zone-header">
            <span class="vpg-zone-icon vpg-row-icon">↓</span>
            <span class="vpg-zone-label">Rows</span>
          </div>
          <div class="vpg-zone-chips">
            <div
              v-for="field in rowFields"
              :key="field"
              class="vpg-mini-chip vpg-row-chip"
            >
              <span class="vpg-mini-name">{{ field }}</span>
              <button class="vpg-mini-remove" @click.stop="emit('removeRowField', field)">×</button>
            </div>
            <span v-if="rowFields.length === 0" class="vpg-zone-hint">Drop here</span>
          </div>
        </div>

        <!-- Column drop zone -->
        <div
          class="vpg-drop-zone vpg-column-zone"
          :class="{ 'vpg-drag-over': dragOverArea === 'column' }"
          @dragover="handleDragOver('column', $event)"
          @dragleave="handleDragLeave"
          @drop="handleDrop('column', $event)"
        >
          <div class="vpg-zone-header">
            <span class="vpg-zone-icon vpg-column-icon">→</span>
            <span class="vpg-zone-label">Columns</span>
          </div>
          <div class="vpg-zone-chips">
            <div
              v-for="field in columnFields"
              :key="field"
              class="vpg-mini-chip vpg-column-chip"
            >
              <span class="vpg-mini-name">{{ field }}</span>
              <button class="vpg-mini-remove" @click.stop="emit('removeColumnField', field)">×</button>
            </div>
            <span v-if="columnFields.length === 0" class="vpg-zone-hint">Drop here</span>
          </div>
        </div>

        <!-- Values drop zone -->
        <div
          class="vpg-drop-zone vpg-value-zone"
          :class="{ 'vpg-drag-over': dragOverArea === 'value' }"
          @dragover="handleDragOver('value', $event)"
          @dragleave="handleDragLeave"
          @drop="handleDrop('value', $event)"
        >
          <div class="vpg-zone-header">
            <span class="vpg-zone-icon vpg-value-icon">Σ</span>
            <span class="vpg-zone-label">Values</span>
          </div>
          <div class="vpg-zone-chips">
            <div
              v-for="vf in valueFields"
              :key="`${vf.field}-${vf.aggregation}`"
              class="vpg-mini-chip vpg-value-chip"
            >
              <span class="vpg-agg-symbol">{{ getAggSymbol(vf.aggregation) }}</span>
              <span class="vpg-mini-name">{{ vf.field }}</span>
              <button class="vpg-mini-remove" @click="emit('removeValueField', vf.field, vf.aggregation)">×</button>
            </div>
            <span v-if="valueFields.length === 0" class="vpg-zone-hint">Drop numeric</span>
          </div>
        </div>
      </div>

      <!-- Placeholder when not configured -->
      <div v-if="!isConfigured || !pivotResult" class="vpg-placeholder">
        <div class="vpg-placeholder-content">
          <svg class="vpg-placeholder-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M3 10h18M3 14h18m-9-4v8m-7 0h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
          <span class="vpg-placeholder-text">
            <template v-if="valueFields.length === 0">
              Add a <strong>Values</strong> field to see your pivot table
            </template>
            <template v-else-if="rowFields.length === 0 && columnFields.length === 0">
              Add <strong>Row</strong> or <strong>Column</strong> fields to group your data
            </template>
            <template v-else>
              Your pivot table will appear here
            </template>
          </span>
        </div>
      </div>

      <!-- Data Table -->
      <div v-else class="vpg-table-container">
        <table class="vpg-pivot-table">
          <thead>
            <tr v-for="(headerRow, levelIdx) in columnHeaderCells" :key="`header-${levelIdx}`" class="vpg-column-header-row">
              <th
                v-if="levelIdx === 0"
                class="vpg-row-header-label"
                :rowspan="columnHeaderCells.length"
                :style="{ width: `${rowHeaderWidth}px` }"
                @click="toggleSort('row')"
              >
                <div class="vpg-header-content">
                  <span>{{ rowFields.join(' / ') || 'Rows' }}</span>
                  <span class="vpg-sort-indicator" :class="{ active: sortTarget === 'row' }">
                    {{ sortTarget === 'row' ? (sortDirection === 'asc' ? '↑' : '↓') : '⇅' }}
                  </span>
                </div>
              </th>
              <th
                v-for="(cell, idx) in headerRow"
                :key="idx"
                class="vpg-column-header-cell"
                :colspan="cell.colspan"
                :style="{ width: `${dataColWidth * cell.colspan}px` }"
                @click="levelIdx === columnHeaderCells.length - 1 && toggleSort(idx)"
              >
                <div class="vpg-header-content">
                  <span>{{ cell.label }}</span>
                  <span v-if="levelIdx === columnHeaderCells.length - 1" class="vpg-sort-indicator" :class="{ active: sortTarget === idx }">
                    {{ sortTarget === idx ? (sortDirection === 'asc' ? '↑' : '↓') : '⇅' }}
                  </span>
                </div>
              </th>
              <th v-if="pivotResult.rowTotals.length > 0 && levelIdx === columnHeaderCells.length - 1" class="vpg-total-header">
                Total
              </th>
            </tr>
          </thead>

          <tbody>
            <tr v-for="sortedIdx in sortedRowIndices" :key="sortedIdx" class="vpg-data-row">
              <th
                class="vpg-row-header-cell"
                :style="{ width: `${rowHeaderWidth}px` }"
              >
                <span v-for="(val, idx) in pivotResult.rowHeaders[sortedIdx]" :key="idx" class="vpg-row-value">
                  {{ val }}
                </span>
              </th>

              <td
                v-for="(cell, colIdx) in pivotResult.data[sortedIdx]"
                :key="colIdx"
                class="vpg-data-cell"
                :class="[
                  isCellSelected(sortedIdx, colIdx) && 'selected',
                  cell.value === null && 'vpg-is-null',
                ]"
                :style="{ width: `${dataColWidth}px` }"
                @click="handleCellClick(sortedIdx, colIdx)"
              >
                {{ cell.formattedValue }}
              </td>

              <td v-if="pivotResult.rowTotals[sortedIdx]" class="vpg-data-cell vpg-total-cell">
                {{ pivotResult.rowTotals[sortedIdx].formattedValue }}
              </td>
            </tr>

            <tr v-if="pivotResult.columnTotals.length > 0" class="vpg-totals-row">
              <th class="vpg-row-header-cell vpg-total-label" :style="{ width: `${rowHeaderWidth}px` }">
                Total
              </th>
              <td
                v-for="(cell, colIdx) in pivotResult.columnTotals"
                :key="colIdx"
                class="vpg-data-cell vpg-total-cell"
                :style="{ width: `${dataColWidth}px` }"
              >
                {{ cell.formattedValue }}
              </td>
              <td v-if="pivotResult.rowTotals.length > 0" class="vpg-data-cell vpg-grand-total-cell">
                {{ pivotResult.grandTotal.formattedValue }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Footer -->
      <div v-if="isConfigured && pivotResult" class="vpg-skeleton-footer">
        <span>{{ pivotResult.rowHeaders.length }} rows × {{ pivotResult.data[0]?.length || 0 }} columns</span>
      </div>
    </template>

    <!-- Watermark / Demo Banner -->
    <div v-if="showWatermark && canUsePivot" class="vpg-watermark" :class="{ 'vpg-demo-mode': isDemo }">
      <template v-if="isDemo">
        <span class="vpg-demo-badge">DEMO</span>
        <span>Pro features unlocked for evaluation</span>
        <a href="https://tiny-pivot.com/pricing" target="_blank" rel="noopener" class="vpg-get-pro">
          Get Pro License →
        </a>
      </template>
      <template v-else>
        <a href="https://tiny-pivot.com" target="_blank" rel="noopener">
          Powered by TinyPivot
        </a>
      </template>
    </div>
  </div>
</template>

<style scoped>
.vpg-pivot-skeleton {
  background: white;
  border: 1px solid #e2e8f0;
  border-radius: 0.75rem;
  box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1);
  overflow: hidden;
  display: flex;
  flex-direction: column;
  height: 100%;
}

.vpg-pivot-skeleton.vpg-is-dragging {
  box-shadow: 0 0 0 2px #10b981;
}

.vpg-icon {
  width: 1rem;
  height: 1rem;
}

/* Header */
.vpg-skeleton-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.5rem 1rem;
  background: linear-gradient(to right, #ecfdf5, #f0fdfa);
  border-bottom: 1px solid #e2e8f0;
  flex-shrink: 0;
}

.vpg-skeleton-title {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.75rem;
  font-weight: 600;
  color: #475569;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.vpg-header-right {
  display: flex;
  align-items: center;
  gap: 0.75rem;
}

.vpg-config-summary {
  display: flex;
  align-items: center;
  gap: 0.375rem;
}

.vpg-summary-badge {
  padding: 0.125rem 0.375rem;
  font-size: 0.625rem;
  font-weight: 600;
  border-radius: 0.25rem;
}

.vpg-summary-badge.vpg-rows {
  background: #e0e7ff;
  color: #4f46e5;
}

.vpg-summary-badge.vpg-cols {
  background: #ede9fe;
  color: #7c3aed;
}

.vpg-summary-badge.vpg-vals {
  background: #d1fae5;
  color: #059669;
}

.vpg-font-size-toggle {
  display: flex;
  background: white;
  border-radius: 0.25rem;
  border: 1px solid #e2e8f0;
  overflow: hidden;
}

.vpg-font-size-btn {
  padding: 0.125rem 0.5rem;
  font-size: 0.625rem;
  font-weight: 500;
  color: #64748b;
  background: transparent;
  border: none;
  cursor: pointer;
  transition: all 0.15s;
}

.vpg-font-size-btn:hover {
  background: #f1f5f9;
}

.vpg-font-size-btn.active {
  background: #10b981;
  color: white;
}

/* Pro Required */
.vpg-pro-required {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #fef3c7, #fde68a);
}

.vpg-pro-content {
  text-align: center;
  padding: 2rem;
}

.vpg-pro-icon {
  width: 3rem;
  height: 3rem;
  color: #d97706;
  margin: 0 auto 1rem;
}

.vpg-pro-content h3 {
  font-size: 1.25rem;
  font-weight: 600;
  color: #92400e;
  margin-bottom: 0.5rem;
}

.vpg-pro-content p {
  font-size: 0.875rem;
  color: #a16207;
  margin-bottom: 1rem;
}

.vpg-pro-link {
  display: inline-block;
  padding: 0.5rem 1rem;
  background: #f59e0b;
  color: white;
  font-weight: 500;
  border-radius: 0.375rem;
  text-decoration: none;
  transition: background 0.15s;
}

.vpg-pro-link:hover {
  background: #d97706;
}

/* Config Bar */
.vpg-config-bar {
  display: flex;
  align-items: stretch;
  gap: 0.5rem;
  padding: 0.5rem 0.75rem;
  background: #f8fafc;
  border-bottom: 1px solid #e2e8f0;
  flex-shrink: 0;
}

.vpg-drop-zone {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 0.75rem;
  border-radius: 0.5rem;
  border: 2px dashed;
  transition: all 0.15s;
}

.vpg-drop-zone.vpg-row-zone {
  background: rgba(238, 242, 255, 0.5);
  border-color: #c7d2fe;
}

.vpg-drop-zone.vpg-column-zone {
  background: rgba(245, 243, 255, 0.5);
  border-color: #ddd6fe;
  flex: 1;
}

.vpg-drop-zone.vpg-value-zone {
  background: rgba(236, 253, 245, 0.5);
  border-color: #a7f3d0;
}

.vpg-drop-zone.vpg-drag-over {
  border-style: solid;
  box-shadow: 0 0 0 2px currentColor inset;
}

.vpg-drop-zone.vpg-row-zone.vpg-drag-over {
  background: #eef2ff;
  border-color: #818cf8;
}

.vpg-drop-zone.vpg-column-zone.vpg-drag-over {
  background: #f5f3ff;
  border-color: #a78bfa;
}

.vpg-drop-zone.vpg-value-zone.vpg-drag-over {
  background: #ecfdf5;
  border-color: #34d399;
}

.vpg-zone-header {
  display: flex;
  align-items: center;
  gap: 0.375rem;
  flex-shrink: 0;
}

.vpg-zone-icon {
  width: 1.25rem;
  height: 1.25rem;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.75rem;
  font-weight: 700;
  border-radius: 0.25rem;
}

.vpg-zone-icon.vpg-row-icon {
  background: #c7d2fe;
  color: #4338ca;
}

.vpg-zone-icon.vpg-column-icon {
  background: #ddd6fe;
  color: #7c3aed;
}

.vpg-zone-icon.vpg-value-icon {
  background: #a7f3d0;
  color: #059669;
}

.vpg-zone-label {
  font-size: 0.625rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.vpg-row-zone .vpg-zone-label {
  color: #4f46e5;
}

.vpg-column-zone .vpg-zone-label {
  color: #7c3aed;
}

.vpg-value-zone .vpg-zone-label {
  color: #059669;
}

.vpg-zone-chips {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 0.25rem;
}

.vpg-zone-hint {
  font-size: 0.625rem;
  color: #94a3b8;
  font-style: italic;
}

.vpg-mini-chip {
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
  padding: 0.25rem 0.5rem;
  border-radius: 0.25rem;
  font-size: 0.625rem;
  font-weight: 500;
  max-width: 100%;
  box-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05);
}

.vpg-mini-chip.vpg-row-chip {
  background: white;
  color: #4338ca;
  border: 1px solid #c7d2fe;
}

.vpg-mini-chip.vpg-column-chip {
  background: white;
  color: #7c3aed;
  border: 1px solid #ddd6fe;
}

.vpg-mini-chip.vpg-value-chip {
  background: white;
  color: #059669;
  border: 1px solid #a7f3d0;
}

.vpg-mini-name {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  flex: 1;
}

.vpg-mini-remove {
  width: 1rem;
  height: 1rem;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.875rem;
  line-height: 1;
  opacity: 0.4;
  flex-shrink: 0;
  background: transparent;
  border: none;
  border-radius: 50%;
  cursor: pointer;
  transition: all 0.15s;
}

.vpg-mini-remove:hover {
  opacity: 1;
  background: #fee2e2;
  color: #ef4444;
}

.vpg-agg-symbol {
  width: 1rem;
  height: 1rem;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.625rem;
  font-weight: 700;
  background: #d1fae5;
  color: #059669;
  border-radius: 0.25rem;
  flex-shrink: 0;
}

/* Placeholder */
.vpg-placeholder {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #f8fafc, white, rgba(236, 253, 245, 0.3));
  border-top: 1px solid #f1f5f9;
}

.vpg-placeholder-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
  text-align: center;
  padding: 2rem;
}

.vpg-placeholder-icon {
  width: 4rem;
  height: 4rem;
  color: #cbd5e1;
}

.vpg-placeholder-text {
  font-size: 0.875rem;
  color: #64748b;
}

.vpg-placeholder-text strong {
  color: #334155;
  font-weight: 600;
}

/* Table */
.vpg-table-container {
  flex: 1;
  overflow: auto;
  max-height: 100%;
}

.vpg-pivot-table {
  border-collapse: collapse;
  table-layout: fixed;
  min-width: max-content;
}

.vpg-pivot-table thead {
  position: sticky;
  top: 0;
  z-index: 30;
  box-shadow: 0 2px 4px -1px rgba(0, 0, 0, 0.1);
}

.vpg-column-header-row {
  background: #e2e8f0;
}

.vpg-column-header-row th {
  background: #e2e8f0;
}

.vpg-row-header-label {
  position: sticky;
  left: 0;
  z-index: 30;
  padding: 0.5rem 0.75rem;
  text-align: left;
  font-size: 0.625rem;
  font-weight: 600;
  color: #64748b;
  text-transform: uppercase;
  border-bottom: 1px solid #cbd5e1;
  border-right: 1px solid #cbd5e1;
  background: #e2e8f0;
  cursor: pointer;
}

.vpg-row-header-label:hover {
  background: #d1d5db;
}

.vpg-column-header-cell {
  padding: 0.5rem 0.75rem;
  text-align: center;
  font-size: 0.6875rem;
  font-weight: 600;
  color: #334155;
  border-bottom: 1px solid #cbd5e1;
  border-right: 1px solid #cbd5e1;
  white-space: nowrap;
  background: #e2e8f0;
  cursor: pointer;
}

.vpg-column-header-cell:hover {
  background: rgba(203, 213, 225, 0.5);
}

.vpg-header-content {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.25rem;
}

.vpg-sort-indicator {
  flex-shrink: 0;
  width: 1rem;
  height: 1rem;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #94a3b8;
  font-size: 0.75rem;
}

.vpg-sort-indicator.active {
  color: #4f46e5;
  font-weight: 700;
}

.vpg-total-header {
  padding: 0.5rem;
  text-align: center;
  font-size: 0.6875rem;
  font-weight: 700;
  color: #92400e;
  border-bottom: 1px solid #cbd5e1;
  background: #fde68a;
}

.vpg-data-row:hover {
  background: rgba(236, 253, 245, 0.3);
}

.vpg-data-row:nth-child(even) {
  background: rgba(248, 250, 252, 0.5);
}

.vpg-row-header-cell {
  position: sticky;
  left: 0;
  padding: 0.5rem 0.75rem;
  text-align: left;
  font-size: 0.75rem;
  font-weight: 500;
  color: #334155;
  background: white;
  border-bottom: 1px solid #e2e8f0;
  border-right: 1px solid #e2e8f0;
  white-space: nowrap;
  z-index: 10;
}

.vpg-data-row:nth-child(even) .vpg-row-header-cell {
  background: rgba(248, 250, 252, 0.5);
}

.vpg-row-value + .vpg-row-value::before {
  content: ' / ';
  color: #94a3b8;
}

.vpg-data-cell {
  padding: 0.5rem 0.75rem;
  text-align: right;
  font-size: 0.75rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
  color: #334155;
  font-variant-numeric: tabular-nums;
  border-bottom: 1px solid #f1f5f9;
  border-right: 1px solid #f8fafc;
  cursor: cell;
  white-space: nowrap;
}

.vpg-data-cell.selected {
  background: #d1fae5;
  outline: 2px solid #10b981;
  outline-offset: -2px;
  position: relative;
  z-index: 1;
}

.vpg-data-cell.vpg-is-null {
  color: #cbd5e1;
}

.vpg-data-cell.vpg-total-cell {
  background: rgba(254, 243, 199, 0.6);
  font-weight: 600;
  color: #92400e;
}

.vpg-data-cell.vpg-grand-total-cell {
  background: #fde68a;
  font-weight: 700;
  color: #92400e;
}

.vpg-totals-row {
  background: rgba(254, 243, 199, 0.4);
}

.vpg-total-label {
  font-weight: 700;
  color: #92400e;
  background: #fef3c7;
}

/* Font sizes */
.vpg-pivot-skeleton.vpg-font-xs .vpg-data-cell,
.vpg-pivot-skeleton.vpg-font-xs .vpg-row-header-cell {
  font-size: 0.75rem;
  padding: 0.375rem 0.75rem;
}

.vpg-pivot-skeleton.vpg-font-sm .vpg-data-cell,
.vpg-pivot-skeleton.vpg-font-sm .vpg-row-header-cell {
  font-size: 0.875rem;
  padding: 0.5rem 1rem;
}

.vpg-pivot-skeleton.vpg-font-base .vpg-data-cell,
.vpg-pivot-skeleton.vpg-font-base .vpg-row-header-cell {
  font-size: 1rem;
  padding: 0.625rem 1rem;
}

/* Footer */
.vpg-skeleton-footer {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.5rem 1rem;
  font-size: 0.75rem;
  color: #64748b;
  background: #f8fafc;
  border-top: 1px solid #e2e8f0;
  flex-shrink: 0;
}

/* Watermark */
.vpg-watermark {
  padding: 0.375rem 1rem;
  background: #f1f5f9;
  border-top: 1px solid #e2e8f0;
  text-align: center;
  flex-shrink: 0;
}

.vpg-watermark a {
  font-size: 0.625rem;
  color: #94a3b8;
  text-decoration: none;
  transition: color 0.15s;
}

.vpg-watermark a:hover {
  color: #64748b;
}

/* Demo Mode Banner */
.vpg-watermark.vpg-demo-mode {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.75rem;
  padding: 0.5rem 1rem;
  background: linear-gradient(135deg, #fef3c7, #fde68a);
  border-top: 1px solid #fcd34d;
  font-size: 0.75rem;
  color: #92400e;
}

.vpg-demo-badge {
  display: inline-flex;
  align-items: center;
  padding: 0.125rem 0.5rem;
  background: #f59e0b;
  color: white;
  font-size: 0.625rem;
  font-weight: 700;
  border-radius: 0.25rem;
  letter-spacing: 0.05em;
}

.vpg-get-pro {
  font-weight: 600;
  color: #d97706 !important;
}

.vpg-get-pro:hover {
  color: #b45309 !important;
  text-decoration: underline;
}

/* Scrollbar */
.vpg-table-container::-webkit-scrollbar {
  width: 0.5rem;
  height: 0.5rem;
}

.vpg-table-container::-webkit-scrollbar-track {
  background: #f1f5f9;
}

.vpg-table-container::-webkit-scrollbar-thumb {
  background: #cbd5e1;
  border-radius: 9999px;
}

.vpg-table-container::-webkit-scrollbar-thumb:hover {
  background: #94a3b8;
}

.vpg-table-container::-webkit-scrollbar-corner {
  background: #f1f5f9;
}
</style>

// packages/react/src/components/PivotSkeleton.tsx
/**
 * Pivot Table Skeleton + Data Display for React
 * Visual layout for pivot configuration and results
 */
import React, { useState, useMemo, useCallback } from 'react'
import type { AggregationFunction, PivotResult, PivotValueField } from '@smallwebco/tinypivot-core'
import { getAggregationLabel, getAggregationSymbol } from '@smallwebco/tinypivot-core'
import { useLicense } from '../hooks/useLicense'

interface ActiveFilter {
  column: string
  valueCount: number
  values: string[]
}

interface PivotSkeletonProps {
  rowFields: string[]
  columnFields: string[]
  valueFields: PivotValueField[]
  isConfigured: boolean
  draggingField: string | null
  pivotResult: PivotResult | null
  fontSize?: 'xs' | 'sm' | 'base'
  activeFilters?: ActiveFilter[] | null
  totalRowCount?: number
  filteredRowCount?: number
  onAddRowField: (field: string) => void
  onRemoveRowField: (field: string) => void
  onAddColumnField: (field: string) => void
  onRemoveColumnField: (field: string) => void
  onAddValueField: (field: string, aggregation: AggregationFunction) => void
  onRemoveValueField: (field: string, aggregation: AggregationFunction) => void
  onUpdateAggregation: (field: string, oldAgg: AggregationFunction, newAgg: AggregationFunction) => void
  onReorderRowFields: (fields: string[]) => void
  onReorderColumnFields: (fields: string[]) => void
}

export function PivotSkeleton({
  rowFields,
  columnFields,
  valueFields,
  isConfigured,
  draggingField,
  pivotResult,
  fontSize = 'xs',
  activeFilters,
  totalRowCount,
  filteredRowCount,
  onAddRowField,
  onRemoveRowField,
  onAddColumnField,
  onRemoveColumnField,
  onAddValueField,
  onRemoveValueField,
  onReorderRowFields,
  onReorderColumnFields,
}: PivotSkeletonProps) {
  const { showWatermark, canUsePivot, isDemo } = useLicense()

  // Drag state
  const [dragOverArea, setDragOverArea] = useState<'row' | 'column' | 'value' | null>(null)
  
  // Reorder drag state
  const [reorderDragSource, setReorderDragSource] = useState<{ zone: 'row' | 'column'; index: number } | null>(null)
  const [reorderDropTarget, setReorderDropTarget] = useState<{ zone: 'row' | 'column'; index: number } | null>(null)

  // Sorting
  type SortTarget = 'row' | number
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('asc')
  const [sortTarget, setSortTarget] = useState<SortTarget>('row')

  const toggleSort = useCallback((target: SortTarget = 'row') => {
    if (sortTarget === target) {
      setSortDirection(prev => (prev === 'asc' ? 'desc' : 'asc'))
    } else {
      setSortTarget(target)
      setSortDirection('asc')
    }
  }, [sortTarget])

  // Sorted row indices
  const sortedRowIndices = useMemo(() => {
    if (!pivotResult) return []

    const indices = pivotResult.rowHeaders.map((_, i) => i)
    const headers = pivotResult.rowHeaders
    const data = pivotResult.data

    indices.sort((a, b) => {
      let cmp: number

      if (sortTarget === 'row') {
        const aHeader = headers[a]?.join(' / ') || ''
        const bHeader = headers[b]?.join(' / ') || ''
        cmp = aHeader.localeCompare(bHeader, undefined, { numeric: true, sensitivity: 'base' })
      } else {
        const colIdx = sortTarget as number
        const aVal = data[a]?.[colIdx]?.value ?? null
        const bVal = data[b]?.[colIdx]?.value ?? null

        if (aVal === null && bVal === null) cmp = 0
        else if (aVal === null) cmp = 1
        else if (bVal === null) cmp = -1
        else cmp = aVal - bVal
      }

      return sortDirection === 'asc' ? cmp : -cmp
    })

    return indices
  }, [pivotResult, sortTarget, sortDirection])

  // Column headers
  const columnHeaderCells = useMemo(() => {
    if (!pivotResult || pivotResult.headers.length === 0) {
      return [
        valueFields.map(vf => ({
          label: `${vf.field} (${getAggregationLabel(vf.aggregation)})`,
          colspan: 1,
        })),
      ]
    }

    const result: Array<Array<{ label: string; colspan: number }>> = []

    for (let level = 0; level < pivotResult.headers.length; level++) {
      const headerRow = pivotResult.headers[level]
      const cells: Array<{ label: string; colspan: number }> = []

      let i = 0
      while (i < headerRow.length) {
        const value = headerRow[i]
        let colspan = 1

        while (i + colspan < headerRow.length && headerRow[i + colspan] === value) {
          colspan++
        }

        cells.push({ label: value, colspan })
        i += colspan
      }

      result.push(cells)
    }

    return result
  }, [pivotResult, valueFields])

  // Filter status
  const hasActiveFilters = activeFilters && activeFilters.length > 0
  const filterSummary = useMemo(() => {
    if (!activeFilters || activeFilters.length === 0) return ''
    return activeFilters.map(f => f.column).join(', ')
  }, [activeFilters])

  // Detailed filter tooltip
  const [showFilterTooltip, setShowFilterTooltip] = useState(false)
  const filterTooltipDetails = useMemo(() => {
    if (!activeFilters || activeFilters.length === 0) return []
    return activeFilters.map(f => {
      const maxDisplay = 5
      const displayValues = f.values.slice(0, maxDisplay)
      const remaining = f.values.length - maxDisplay
      return {
        column: f.column,
        values: displayValues,
        remaining: remaining > 0 ? remaining : 0,
      }
    })
  }, [activeFilters])

  // Drag handlers
  const handleDragOver = useCallback(
    (area: 'row' | 'column' | 'value', event: React.DragEvent) => {
      event.preventDefault()
      event.dataTransfer!.dropEffect = 'move'
      setDragOverArea(area)
    },
    []
  )

  const handleDragLeave = useCallback(() => {
    setDragOverArea(null)
  }, [])

  const handleDrop = useCallback(
    (area: 'row' | 'column' | 'value', event: React.DragEvent) => {
      event.preventDefault()
      const field = event.dataTransfer?.getData('text/plain')

      if (!field || field.startsWith('reorder:')) {
        setDragOverArea(null)
        return
      }

      if (rowFields.includes(field)) onRemoveRowField(field)
      if (columnFields.includes(field)) onRemoveColumnField(field)
      const existingValue = valueFields.find(v => v.field === field)
      if (existingValue) onRemoveValueField(field, existingValue.aggregation)

      switch (area) {
        case 'row':
          onAddRowField(field)
          break
        case 'column':
          onAddColumnField(field)
          break
        case 'value':
          onAddValueField(field, 'sum')
          break
      }
      setDragOverArea(null)
    },
    [rowFields, columnFields, valueFields, onAddRowField, onRemoveRowField, onAddColumnField, onRemoveColumnField, onAddValueField, onRemoveValueField]
  )

  // Reorder handlers for chips within zones
  const handleChipDragStart = useCallback(
    (zone: 'row' | 'column', index: number, event: React.DragEvent) => {
      setReorderDragSource({ zone, index })
      event.dataTransfer!.effectAllowed = 'move'
      event.dataTransfer!.setData('text/plain', `reorder:${zone}:${index}`)
      // Clear any zone drag-over state
      requestAnimationFrame(() => {
        setDragOverArea(null)
      })
    },
    []
  )

  const handleChipDragEnd = useCallback(() => {
    setReorderDragSource(null)
    setReorderDropTarget(null)
  }, [])

  const handleChipDragOver = useCallback(
    (zone: 'row' | 'column', index: number, event: React.DragEvent) => {
      event.preventDefault()
      // Only handle reorder within same zone
      if (reorderDragSource && reorderDragSource.zone === zone) {
        event.dataTransfer!.dropEffect = 'move'
        setReorderDropTarget({ zone, index })
      }
    },
    [reorderDragSource]
  )

  const handleChipDragLeave = useCallback(() => {
    setReorderDropTarget(null)
  }, [])

  const handleChipDrop = useCallback(
    (zone: 'row' | 'column', targetIndex: number, event: React.DragEvent) => {
      event.preventDefault()
      event.stopPropagation()

      if (!reorderDragSource || reorderDragSource.zone !== zone) {
        return
      }

      const sourceIndex = reorderDragSource.index
      if (sourceIndex === targetIndex) {
        setReorderDragSource(null)
        setReorderDropTarget(null)
        return
      }

      // Create reordered array
      const fields = zone === 'row' ? [...rowFields] : [...columnFields]
      const [movedField] = fields.splice(sourceIndex, 1)
      fields.splice(targetIndex, 0, movedField)

      // Emit reorder event
      if (zone === 'row') {
        onReorderRowFields(fields)
      } else {
        onReorderColumnFields(fields)
      }

      setReorderDragSource(null)
      setReorderDropTarget(null)
    },
    [reorderDragSource, rowFields, columnFields, onReorderRowFields, onReorderColumnFields]
  )

  const isChipDragSource = useCallback(
    (zone: 'row' | 'column', index: number): boolean => {
      return reorderDragSource?.zone === zone && reorderDragSource?.index === index
    },
    [reorderDragSource]
  )

  const isChipDropTarget = useCallback(
    (zone: 'row' | 'column', index: number): boolean => {
      return reorderDropTarget?.zone === zone && reorderDropTarget?.index === index
    },
    [reorderDropTarget]
  )

  const currentFontSize = fontSize

  return (
    <div
      className={`vpg-pivot-skeleton vpg-font-${currentFontSize} ${draggingField ? 'vpg-is-dragging' : ''}`}
    >
      {/* Header Bar */}
      <div className="vpg-skeleton-header">
        <div className="vpg-skeleton-title">
          <svg className="vpg-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z"
            />
          </svg>
          <span>Pivot Table</span>
        </div>

        <div className="vpg-header-right">
          {hasActiveFilters && (
            <div
              className="vpg-filter-indicator"
              onMouseEnter={() => setShowFilterTooltip(true)}
              onMouseLeave={() => setShowFilterTooltip(false)}
            >
              <svg
                className="vpg-filter-icon"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M3 4a1 1 0 011-1h16a1 1 0 011 1v2.586a1 1 0 01-.293.707l-6.414 6.414a1 1 0 00-.293.707V17l-4 4v-6.586a1 1 0 00-.293-.707L3.293 7.293A1 1 0 013 6.586V4z"
                />
              </svg>
              <span className="vpg-filter-text">
                Filtered: <strong>{filterSummary}</strong>
                {filteredRowCount !== undefined && totalRowCount !== undefined && (
                  <span className="vpg-filter-count">
                    ({filteredRowCount.toLocaleString()} of {totalRowCount.toLocaleString()} rows)
                  </span>
                )}
              </span>

              {/* Tooltip */}
              {showFilterTooltip && (
                <div className="vpg-filter-tooltip">
                  <div className="vpg-tooltip-header">Active Filters</div>
                  {filterTooltipDetails.map(filter => (
                    <div key={filter.column} className="vpg-tooltip-filter">
                      <div className="vpg-tooltip-column">{filter.column}</div>
                      <div className="vpg-tooltip-values">
                        {filter.values.map((val, idx) => (
                          <span key={idx} className="vpg-tooltip-value">
                            {val}
                          </span>
                        ))}
                        {filter.remaining > 0 && (
                          <span className="vpg-tooltip-more">+{filter.remaining} more</span>
                        )}
                      </div>
                    </div>
                  ))}
                  {filteredRowCount !== undefined && totalRowCount !== undefined && (
                    <div className="vpg-tooltip-summary">
                      Showing {filteredRowCount.toLocaleString()} of {totalRowCount.toLocaleString()} rows
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {isConfigured && (
            <div className="vpg-config-summary">
              <span className="vpg-summary-badge vpg-rows">
                {rowFields.length} row{rowFields.length !== 1 ? 's' : ''}
              </span>
              <span className="vpg-summary-badge vpg-cols">
                {columnFields.length} col{columnFields.length !== 1 ? 's' : ''}
              </span>
              <span className="vpg-summary-badge vpg-vals">
                {valueFields.length} val{valueFields.length !== 1 ? 's' : ''}
              </span>
            </div>
          )}
        </div>
      </div>

      {/* License Required Message */}
      {!canUsePivot ? (
        <div className="vpg-pro-required">
          <div className="vpg-pro-content">
            <svg className="vpg-pro-icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
              />
            </svg>
            <h3>Pro Feature</h3>
            <p>Pivot Table functionality requires a Pro license.</p>
            <a href="https://tiny-pivot.com/#pricing" target="_blank" rel="noopener noreferrer" className="vpg-pro-link">
              Get Pro License →
            </a>
          </div>
        </div>
      ) : (
        <>
          {/* Config Bar */}
          <div className="vpg-config-bar">
            {/* Row drop zone */}
            <div
              className={`vpg-drop-zone vpg-row-zone ${dragOverArea === 'row' ? 'vpg-drag-over' : ''}`}
              onDragOver={e => handleDragOver('row', e)}
              onDragLeave={handleDragLeave}
              onDrop={e => handleDrop('row', e)}
            >
              <div className="vpg-zone-header">
                <span className="vpg-zone-icon vpg-row-icon">↓</span>
                <span className="vpg-zone-label">Rows</span>
              </div>
              <div className="vpg-zone-chips">
                {rowFields.map((field, idx) => (
                  <div
                    key={field}
                    className={`vpg-mini-chip vpg-row-chip ${isChipDragSource('row', idx) ? 'vpg-chip-dragging' : ''} ${isChipDropTarget('row', idx) ? 'vpg-chip-drop-target' : ''}`}
                    draggable
                    onDragStart={e => handleChipDragStart('row', idx, e)}
                    onDragEnd={handleChipDragEnd}
                    onDragOver={e => handleChipDragOver('row', idx, e)}
                    onDragLeave={handleChipDragLeave}
                    onDrop={e => handleChipDrop('row', idx, e)}
                  >
                    <span className="vpg-drag-handle">⋮⋮</span>
                    <span className="vpg-mini-name">{field}</span>
                    <button
                      className="vpg-mini-remove"
                      onClick={e => { e.stopPropagation(); onRemoveRowField(field) }}
                    >
                      ×
                    </button>
                  </div>
                ))}
                {rowFields.length === 0 && <span className="vpg-zone-hint">Drop here</span>}
              </div>
            </div>

            {/* Column drop zone */}
            <div
              className={`vpg-drop-zone vpg-column-zone ${dragOverArea === 'column' ? 'vpg-drag-over' : ''}`}
              onDragOver={e => handleDragOver('column', e)}
              onDragLeave={handleDragLeave}
              onDrop={e => handleDrop('column', e)}
            >
              <div className="vpg-zone-header">
                <span className="vpg-zone-icon vpg-column-icon">→</span>
                <span className="vpg-zone-label">Columns</span>
              </div>
              <div className="vpg-zone-chips">
                {columnFields.map((field, idx) => (
                  <div
                    key={field}
                    className={`vpg-mini-chip vpg-column-chip ${isChipDragSource('column', idx) ? 'vpg-chip-dragging' : ''} ${isChipDropTarget('column', idx) ? 'vpg-chip-drop-target' : ''}`}
                    draggable
                    onDragStart={e => handleChipDragStart('column', idx, e)}
                    onDragEnd={handleChipDragEnd}
                    onDragOver={e => handleChipDragOver('column', idx, e)}
                    onDragLeave={handleChipDragLeave}
                    onDrop={e => handleChipDrop('column', idx, e)}
                  >
                    <span className="vpg-drag-handle">⋮⋮</span>
                    <span className="vpg-mini-name">{field}</span>
                    <button
                      className="vpg-mini-remove"
                      onClick={e => { e.stopPropagation(); onRemoveColumnField(field) }}
                    >
                      ×
                    </button>
                  </div>
                ))}
                {columnFields.length === 0 && <span className="vpg-zone-hint">Drop here</span>}
              </div>
            </div>

            {/* Values drop zone */}
            <div
              className={`vpg-drop-zone vpg-value-zone ${dragOverArea === 'value' ? 'vpg-drag-over' : ''}`}
              onDragOver={e => handleDragOver('value', e)}
              onDragLeave={handleDragLeave}
              onDrop={e => handleDrop('value', e)}
            >
              <div className="vpg-zone-header">
                <span className="vpg-zone-icon vpg-value-icon">Σ</span>
                <span className="vpg-zone-label">Values</span>
              </div>
              <div className="vpg-zone-chips">
                {valueFields.map(vf => (
                  <div
                    key={`${vf.field}-${vf.aggregation}`}
                    className="vpg-mini-chip vpg-value-chip"
                  >
                    <span className="vpg-agg-symbol">{getAggregationSymbol(vf.aggregation)}</span>
                    <span className="vpg-mini-name">{vf.field}</span>
                    <button
                      className="vpg-mini-remove"
                      onClick={() => onRemoveValueField(vf.field, vf.aggregation)}
                    >
                      ×
                    </button>
                  </div>
                ))}
                {valueFields.length === 0 && <span className="vpg-zone-hint">Drop numeric</span>}
              </div>
            </div>
          </div>

          {/* Placeholder when not configured */}
          {(!isConfigured || !pivotResult) && (
            <div className="vpg-placeholder">
              <div className="vpg-placeholder-content">
                <svg
                  className="vpg-placeholder-icon"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={1.5}
                    d="M3 10h18M3 14h18m-9-4v8m-7 0h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"
                  />
                </svg>
                <span className="vpg-placeholder-text">
                  {valueFields.length === 0 ? (
                    <>
                      Add a <strong>Values</strong> field to see your pivot table
                    </>
                  ) : rowFields.length === 0 && columnFields.length === 0 ? (
                    <>
                      Add <strong>Row</strong> or <strong>Column</strong> fields to group your data
                    </>
                  ) : (
                    'Your pivot table will appear here'
                  )}
                </span>
              </div>
            </div>
          )}

          {/* Data Table */}
          {isConfigured && pivotResult && (
            <div className="vpg-table-container">
              <table className="vpg-pivot-table">
                <thead>
                  {columnHeaderCells.map((headerRow, levelIdx) => (
                    <tr key={`header-${levelIdx}`} className="vpg-column-header-row">
                      {levelIdx === 0 && (
                        <th
                          className="vpg-row-header-label"
                          rowSpan={columnHeaderCells.length}
                          onClick={() => toggleSort('row')}
                        >
                          <div className="vpg-header-content">
                            <span>{rowFields.join(' / ') || 'Rows'}</span>
                            <span className={`vpg-sort-indicator ${sortTarget === 'row' ? 'active' : ''}`}>
                              {sortTarget === 'row' ? (sortDirection === 'asc' ? '↑' : '↓') : '⇅'}
                            </span>
                          </div>
                        </th>
                      )}
                      {headerRow.map((cell, idx) => (
                        <th
                          key={idx}
                          className="vpg-column-header-cell"
                          colSpan={cell.colspan}
                          onClick={() =>
                            levelIdx === columnHeaderCells.length - 1 && toggleSort(idx)
                          }
                        >
                          <div className="vpg-header-content">
                            <span>{cell.label}</span>
                            {levelIdx === columnHeaderCells.length - 1 && (
                              <span className={`vpg-sort-indicator ${sortTarget === idx ? 'active' : ''}`}>
                                {sortTarget === idx
                                  ? sortDirection === 'asc'
                                    ? '↑'
                                    : '↓'
                                  : '⇅'}
                              </span>
                            )}
                          </div>
                        </th>
                      ))}
                      {pivotResult.rowTotals.length > 0 && levelIdx === 0 && (
                        <th className="vpg-total-header" rowSpan={columnHeaderCells.length}>
                          Total
                        </th>
                      )}
                    </tr>
                  ))}
                </thead>

                <tbody>
                  {sortedRowIndices.map(sortedIdx => (
                    <tr key={sortedIdx} className="vpg-data-row">
                      <th className="vpg-row-header-cell">
                        {pivotResult.rowHeaders[sortedIdx].map((val, idx) => (
                          <span key={idx} className="vpg-row-value">
                            {val}
                          </span>
                        ))}
                      </th>

                      {pivotResult.data[sortedIdx].map((cell, colIdx) => (
                        <td
                          key={colIdx}
                          className={`vpg-data-cell ${cell.value === null ? 'vpg-is-null' : ''}`}
                        >
                          {cell.formattedValue}
                        </td>
                      ))}

                      {pivotResult.rowTotals[sortedIdx] && (
                        <td className="vpg-data-cell vpg-total-cell">
                          {pivotResult.rowTotals[sortedIdx].formattedValue}
                        </td>
                      )}
                    </tr>
                  ))}

                  {pivotResult.columnTotals.length > 0 && (
                    <tr className="vpg-totals-row">
                      <th className="vpg-row-header-cell vpg-total-label">Total</th>
                      {pivotResult.columnTotals.map((cell, colIdx) => (
                        <td key={colIdx} className="vpg-data-cell vpg-total-cell">
                          {cell.formattedValue}
                        </td>
                      ))}
                      {pivotResult.rowTotals.length > 0 && (
                        <td className="vpg-data-cell vpg-grand-total-cell">
                          {pivotResult.grandTotal.formattedValue}
                        </td>
                      )}
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          )}

          {/* Footer */}
          {isConfigured && pivotResult && (
            <div className="vpg-skeleton-footer">
              <span>
                {pivotResult.rowHeaders.length} rows × {pivotResult.data[0]?.length || 0} columns
              </span>
            </div>
          )}
        </>
      )}

      {/* Watermark / Demo Banner */}
      {showWatermark && canUsePivot && (
        <div className={`vpg-watermark ${isDemo ? 'vpg-demo-mode' : ''}`}>
          {isDemo ? (
            <>
              <span className="vpg-demo-badge">DEMO</span>
              <span>Pro features unlocked for evaluation</span>
              <a
                href="https://tiny-pivot.com/#pricing"
                target="_blank"
                rel="noopener noreferrer"
                className="vpg-get-pro"
              >
                Get Pro License →
              </a>
            </>
          ) : (
            <a href="https://tiny-pivot.com" target="_blank" rel="noopener noreferrer">
              Powered by TinyPivot
            </a>
          )}
        </div>
      )}
    </div>
  )
}
