// examples/studio-react-demo/src/App.tsx
import { createIndexedDBStorage } from '@smallwebco/tinypivot-storage-indexeddb'
import { TinyPivotStudio } from '@smallwebco/tinypivot-studio-react'
import { useState } from 'react'

const storage = createIndexedDBStorage()

// User ID for datasource operations
// NOTE: These must match what was used when creating datasources
const userId = 'demo-user'
// User key for credential encryption (in production, derive from user's auth)
const userKey = 'demo-user-key-for-encryption'
// API endpoint for all server operations (datasources, queries, AI)
const apiEndpoint = '/api/tinypivot'

// AI Analyst configuration
const aiAnalystConfig = {
  endpoint: apiEndpoint,
}

function App() {
  const [theme, setTheme] = useState<'light' | 'dark'>('light')

  return (
    <div style={{ height: '100vh', position: 'relative' }}>
      <TinyPivotStudio
        userId={userId}
        userKey={userKey}
        apiEndpoint={apiEndpoint}
        storage={storage}
        theme={theme}
        aiAnalyst={aiAnalystConfig}
        onPageSave={page => console.log('Page saved:', page)}
        onWidgetSave={widget => console.log('Widget saved:', widget)}
      />
      {/* Theme toggle button */}
      <button
        onClick={() => setTheme(t => t === 'light' ? 'dark' : 'light')}
        style={{
          position: 'fixed',
          bottom: '16px',
          right: '16px',
          padding: '8px 16px',
          borderRadius: '6px',
          border: '1px solid #cbd5e1',
          background: theme === 'light' ? '#ffffff' : '#1e293b',
          color: theme === 'light' ? '#334155' : '#e2e8f0',
          cursor: 'pointer',
          fontSize: '14px',
          zIndex: 1000,
        }}
      >
        {theme === 'light' ? '🌙 Dark' : '☀️ Light'}
      </button>
    </div>
  )
}

export default App

// examples/studio-vue-demo/src/App.vue
<script setup lang="ts">
import type { Page, WidgetConfig } from '@smallwebco/tinypivot-studio-vue'
import { createIndexedDBStorage } from '@smallwebco/tinypivot-storage-indexeddb'
import { TinyPivotStudio } from '@smallwebco/tinypivot-studio-vue'
import { ref } from 'vue'
import '@smallwebco/tinypivot-studio-vue/style.css'

const storage = createIndexedDBStorage()
const theme = ref<'light' | 'dark'>('light')

// User ID for datasource operations
// NOTE: These must match what was used when creating datasources
const userId = 'demo-user'
// User key for credential encryption (in production, derive from user's auth)
const userKey = 'demo-user-key-for-encryption'

// API endpoint for all server operations (datasources, queries, AI)
const apiEndpoint = '/api/tinypivot'

// AI Analyst configuration
const aiAnalystConfig = {
  endpoint: apiEndpoint,
}

function handlePageSave(page: Page) {
  console.log('Page saved:', page)
}

function handleWidgetSave(widget: WidgetConfig) {
  console.log('Widget saved:', widget)
}

function toggleTheme() {
  theme.value = theme.value === 'light' ? 'dark' : 'light'
}
</script>

<template>
  <div style="height: 100vh; position: relative">
    <TinyPivotStudio
      :user-id="userId"
      :storage="storage"
      :theme="theme"
      :api-endpoint="apiEndpoint"
      :user-key="userKey"
      :ai-analyst="aiAnalystConfig"
      @page-save="handlePageSave"
      @widget-save="handleWidgetSave"
    />
    <!-- Theme toggle button -->
    <button
      :style="{
        position: 'fixed',
        bottom: '16px',
        right: '16px',
        padding: '8px 16px',
        borderRadius: '6px',
        border: '1px solid #cbd5e1',
        background: theme === 'light' ? '#ffffff' : '#1e293b',
        color: theme === 'light' ? '#334155' : '#e2e8f0',
        cursor: 'pointer',
        fontSize: '14px',
        zIndex: 1000,
      }"
      @click="toggleTheme"
    >
      {{ theme === 'light' ? '🌙 Dark' : '☀️ Light' }}
    </button>
  </div>
</template>
